[[work-experience-short]]
== icon:file-text[] Work Experience

[cols="2,2,6,3", options="noheader", stripes=odd]
|===
// | icon:calendar[] *FROM*
// | icon:calendar[] *TO*
// | <<#ANCHOR,*TITLE*>>
// | *COMPANY*

// 4+| CONTENT

| icon:calendar[] *Sep 2023*
| icon:calendar[] *Apr 2024*
| <<#Hampr,*Senior Software Engineer*>>
| *Hampr*

4+| Contributed a large variety of changes across 4 projects, both back-end and front-end, including new features, bug fixes, component re-designs, and more. +
Started a project to re-design and modernise the existing legacy projects to bring them to up to 2024 code and architecture standards. +
Started a project to uplift the existing cloud architecture to introduce modern cloud technologies, and to automate all cloud interactions with IaC.

| icon:calendar[] *Mar 2023*
| icon:calendar[] *Sep 2023*
| <<#Socialites,*Principal Engineer*>>
| *Socialites*

4+| As a Principal Engineer at a brand new start-up, I played a pivotal role in designing and building the entire platform from scratch. +
I created functional designs, wireframes, and specifications, and implemented the front-end using React and Next JS, the back-end using Spring Boot, and DevOps components for hosting on AWS with containers over ECS Fargate. +
I ensured full observability using the Grafana stack for logs, traces, and metrics.

| icon:calendar[] *Oct 2022*
| icon:calendar[] *Mar 2023*
| <<#Consunet,*Software Architect*>>
| *Consunet*

4+| Designed and developed a one-size-fits-all flat-file integration service. +
Also evaluated and tested Kubernetes security toolsets, as well as contributing to corporate DevSecOps maturity model.

| icon:calendar[] *Mar 2021*
| icon:calendar[] *Sep 2022*
| <<#CPXSoftwareArchitect,*Software Architect*>>
| *Complexica*

4+| *Lead multiple teams* to develop new software, while designing and developing next generation cloud architectures.

| icon:calendar[] *Dec 2020*
| icon:calendar[] *Mar 2021*
| <<#CPXDeveloper,*Software Developer*>>
| *Complexica*

4+| Developed new functionality for legacy application, uplifted styles to be more modern.

| icon:calendar[] *May 2018*
| icon:calendar[] *Jul 2020*
| <<#TeamLeader,*Support Team Leader / Application Developer*>>
| *CentricMinds*

4+| *Lead a team* of support developers, providing application support to clients. Trained new developers. Served as *escalation point/SME* (L2/L3). Various DevOps, and Architecture duties. +
Also frequently acted as project overflow due to staffing shortages, being involved in feature development on the flagship product, as well as developing several new applications from scratch.

| icon:calendar[] *Jan 2017*
| icon:calendar[] *May 2018*
| <<#Developer,*Support Developer*>>
| *CentricMinds*

4+| Provided enterprise application support to clients. Involved with *feature development, bug fixes, and patches*.

| icon:calendar[] *Nov 2016*
| icon:calendar[] *Jan 2017*
| <<#KM,*Knowledge Management Analyst*>>
| *HP Enterprises*

4+| Responsible for *creating and maintaining knowledge articles* for entire service desk. *Built automation* for almost the entire process which was previously entirely manual.

| icon:calendar[] *Feb 2016*
| icon:calendar[] *Nov 2016*
| <<#CaseManager,*Case Manager*>>
| *HP Enterprises*

4+| First point of contact for on-site technicians during the *upgrade of the Commonwealth Bank branch environment*. Issue fixes, tracking, prevention.

| icon:calendar[] *Sep 2015*
| icon:calendar[] *Feb 2016*
| <<#ServiceDesk,*Service Desk Analyst*>>
| *HP Enterprises*

4+| Desktop and applications support for Commonwealth Bank staff. 
|===
