[[work-experience-extended]]
== icon:file-text[] Work Experience Extended

// === icon:play[] TITLE at COMPANY [[ANCHOR]]
// icon:calendar[] `MONTH YEAR to MONTH YEAR` +
// icon:terminal[] Platform: {url-code}[Company, role="external", window="_blank"] +

// CONTENT

=== icon:play[] Software Architect at Consunet [[Consunet]]
icon:calendar[] `Oct 2022 to Current` +

* Designed a one-size-fits-all integration solution to integrate any flat file provided by the client into software ecosystem
** Small set of NodeJS microservices which would listen to file changes on a source file system, then trigger parsing and upserting of provided data into the appropriate data stores
* Evaluated and tested multiple solutions to automate vulnerability scanning and penetration testing of Kubernetes clusters
* Contributed to evaluation and development of corporate DevSecOps maturity model


=== icon:play[] Software Architect at Complexica [[CPXSoftwareArchitect]]
icon:calendar[] `Mar 2021 to Sep 2022` +
icon:terminal[] Clients: Dulux Group, Flinders Port Holdings, Johnson & Johnson

.Multiple projects
* Customer Opportunity Profiler (Dulux Group)
** After completing the project in my previous role, I lead a team of 3 developers to add 2 new BUs to the same application
* Yard Optimisation Project (Flinders Port Holdings)
** Acted as the *sole architect/developer* for a new application.
** The application is responsible for providing real-time recommendations to container terminal clerks on which containers should be moved and where based on future planning and optimised yard configuration.
* Customer Engagement Index Project (Johnson & Johnson)
** *Lead a team to develop a new application* for J&J to track and predict the engagement of their health care professionals.


.Experience
* Leadership
** Ran a team of 3 data scientists and 3 developers for Johnson & Johnson project
** Ran an internal DevOps committee to set in place solid processes and best practices
* Design/Architecture/DevOps
** Worked directly with client team to design the application
** Designed/implemented hybrid (WebFlux/WebMVC/Flask) environments of microservices to accomplish business goals
** Designed/implemented cloud infrastructure/architecture in AWS to host the application efficiently
** Designed/implemented IaC codebase to control AWS infrastructure (using AWS CDK)
** Set in place high quality development standards for other developers
* Development
** Implemented multiple microservices using various technologies and languages to fit client requirements
** Created multiple project templates to be re-used when creating new services
** Created multiple AWS CDK infrastructure projects to fit the specific needs of each project in an optimal, cost-efficient manner

****
.Specific Highlights
* Optimised developer workflow
** Created local developer environment using Docker and Docker Compose to orchestrate all microservices and backing resources to run in hot-reloadable containers.
** This eliminated the need to stop/build/run individual services/containers manually, and the entire environment could be run using simple `make` commands
* Created company's first fully containerised application (x2)
** The 2 projects listed above are Complexica's first to be fully containerised and run efficiently in AWS ECS via Fargate
** The projects consist of a mixture of front-end, back-end, and machine learning services working in tandem
****

*Technologies used:* +
Java, Spring Boot, Python, PostgreSQL, MongoDB, Docker, Docker-Compose, ReactJS, NextJS, Material UI, JavaScript, Typescript, HTML, CSS, +
AWS (CDK, ECS, EC2, ASM, SM, CloudFormation, IAM, Route53, VPC, S3, CloudWatch) +
Git, BitBucket, Jira, Confluence, Shell scripting, Batch scripting

=== icon:play[] Software Developer at Complexica [[CPXDeveloper]]
icon:calendar[] `Dec 2020 to Mar 2021` +
icon:terminal[] Client: Dulux Group

Added new BU to legacy Customer Opportunity Profiler (COP) application and modernised the layout/styling of this application.

* Development
** Added new functionality per client requirements
** Found best available technologies/techniques compatible with legacy versions of the application (React 0.14, Spring Boot 1.25)
** Modernised outdated visual aspects of application with latest design concepts and best practices
** Optimised multiple existing functionalities
*** In one case I reduced the time taken for a certain report to generate from 46 minutes to under 30 seconds
*** In another case I reduced the pre-processing time on a nightly cron job from 13 hours to under 2 hours

Completion of project resulted in 4 new client projects to add additional BUs to the application.

*Technologies used:* +
Java, Spring Boot, PostgreSQL, Docker, Docker-Compose, ReactJS, JavaScript, HTML, CSS, +
AWS (EC2, CloudFormation, IAM, Route53, VPC, S3)
Git, Jenkins, Nexus, BitBucket, Jira, Confluence, Shell scripting

=== icon:play[] Support Team Leader / Application Developer at CentricMinds [[TeamLeader]]
icon:calendar[] `May 2018 to Jul 2020` +
icon:terminal[] Platform: {url-centric}[CentricMinds, role="external", window="_blank"] +

Primarily lead the support development team in all tasks mentioned in below role. Otherwise, filled all technical personnel gaps as required, acting as *2IC* to the CTO.

* Development
** Client driven *feature development* (project based)
** Internally driven feature development (both frontend and backend)
** Liaised with clients and their vendors on technical requirements and *project planning*
** Code reviews
** Prepared internal *documentation* for all technical processes
** Large scale functionality investigations and fixes (both application, and server level)
** Post-mortem investigations and reporting
* Leadership
** *On-boarding and training* of all new developers
** Assignment and *time management* of all support staff
** L2 *technical escalation* for all internal issues
** Revamped entire client-facing support process to *improve overall efficiency/performance*
** Team *performance oversight* and correction
** Involved in *developer hiring* process (selection, interviews)
* DevOps / System Architecture / Software Architecture
** Created new *build server* with latest software and updated CI pipelines
*** Unified previously statically run Docker containers for Jenkins and Nexus into an environment orchestrated by Docker-Compose with self-renewing TLS certificates
** Created various deployment scripts to aid in manual rollouts
** Configured *automated monitoring* and alerts
** Designed and *implemented new architectures* for custom client needs
** Configured *SQL Server replication* for clients
* Quality Control
** Updated code *quality standards* including style and efficiency
** Updated and fixed bloated *dependency management*

****
.Provided platform functionality (highlights)
* Platform upgrade automation
** When I started at CentricMinds the upgrade process for the platform was entirely manual, being performed annually for each client. Upgrading a client's environment to the latest version took approximately a week, and required the developer to manually deploy the platform to each server individually, merge configuration files, upgrade the database schema, etc. Early in my tenure I identified this as a major bottleneck and presented a 7-page project proposal to management, and was tasked with automating the process. 
** I built a module within the platform itself to allow it to self-upgrade to the latest version across multiple servers, effectively in a single step.
* Usage statistics/monitoring platform
** Developed a new suite of REST APIs to provide aggregated platform usage statistics for a React based analytics dashboard
* Support performance metrics platform
** Built a new Spring Boot application to interact with the FreshDesk API to aggregate all statistics on support activities for a given time period. This aggregated data was combined to provide an effective snapshot of a developer's performance.
** This new application also allowed automation of SLA reporting which previously was a manual task involving manipulation of CSV files, Google Drive sheets, and PDF generation.
* Rebuilt legacy custom user sync as Spring Boot app to use new API
** Prior to my joining the team, there existed a user sync application custom built for one client which was responsible for syncing accounts within their own internal database to the CentricMinds platform using our APIs (this version used our legacy SOAP endpoints).
** When their platform was upgraded (see platform automation point above), many of these SOAP endpoints were non-functional, so this sync application needed to be uplifted to interact with the newer REST API endpoints.
** Instead of uplifting the existing ~40,000 lines of C# code, I opted to build a new Spring Boot application. This application ended up being <1000 lines of code, and had the benefit of additional functionality and fault tolerance that the previous app lacked.
* Uplifted SAML SSO middleware (written in Node.js/Express) to be more dynamic and easier to set up, including full documentation and deployment strategies
* Contributed to frontend facelift project
** Replaced many frontend modules (written in JSP) to use an improved look and feel
* Standardised and cleaned up internal logging functionality
* Third party integration
** Uplifted a regularly failing PDF generation suite (Open Office, Libre Office, OfficeToPDF) to be more dynamic and fault tolerant
** Built new integration with ZenDesk APIs, allowing users to submit and view tickets to ZenDesk from within our CMS.
** Updated Active Directory user sync
****

*Technologies used:* +
Java, JSP, Tomcat, Spring Boot, Apache, MySQL, SQL Server, SQLite, NodeJS, Express, Groovy, ElasticSearch, Lucene, JavaScript, HTML, CSS, +
Linux server (Ubuntu, RHEL, CentOS), Windows Server (2008, 2012, 2019), IIS, +
AWS (EC2, ELB, S3, IAM, RDS, VPC, VPN, WAF, Route53, CloudFlare, CloudWatch), Azure (VM, Database for MySQL/SQL Server, Virtual Network, VPN Gateway, Active Directory, Storage), +
Git, Jenkins, Nexus, BitBucket, Shell scripting, Batch scripting, 

<<<

'''

=== icon:play[] Support Developer at CentricMinds [[Developer]]

icon:calendar[] `Jan 2017 to May 2018` +
icon:terminal[] Platform: {url-centric}[CentricMinds, role="external", window="_blank"] +

Provided enterprise level application support to clients for the *Content Management System*, while developing new features, and fixing existing bugs.

* Assisted clients with usage of the platform
** Contributed detailed platform tutorials to *user-guide*
** Debugged application issues and resolved with code changes
** Maintained databases (*MySQL/SQL Server*) for clients
** Performed full application upgrades manually
* Performed *server maintenance* (both cloud and on-premise)
** Performed *infrastructure maintenance* on a regular basis
** Updated software, dependencies
** Configured and maintained *SSL/TLS*
** Installed, configured, updated *Tomcat servers*
* Designed and developed new features
** Automated full application upgrade process
** Built multiple prototypes for new features including *various automation*
* Assisted Support Team Leader
** Revamped infrastructure reporting procedures
** *Created new processes* for development team
** *Trained* new developers
** Provided statistics and reporting to CEO

*Technologies used:* +
Java, Tomcat, MySQL, SQL Server, JavaScript, Git, Groovy, HTML, Jenkins, Nexus, BitBucket, Shell scripting, Batch scripting, AWS (EC2, ELB, RDS, VPC, VPN, CloudFlare), Linux server (Ubuntu, RHEL, CentOS), Windows Server (2008, 2012), IIS

'''

=== icon:play[] Knowledge Management Analyst at HPE [[KM]]
icon:calendar[] `Nov 2016 to Jan 2017` +
icon:bank[] Client: Commonwealth Bank Of Australia

Consolidated all Knowledge Management (KM) tasks previously performed by all SMEs in their spare time under one role.

* Communicated with Service Owners regarding regular KM review process
* Collaborated with Data & Analytics Lead to create new reports to streamline review process
* Contributed to design of several features/enhancements to the in-house service desk application
* Automated identification of recurring issues in KM articles 
** Built and managed a team to assist with major issues resolution
* Built Java application connected to existing knowledgebase SQL Server database for automated issue detection

<<<

'''

=== icon:play[] Project Case Manager at HPE [[CaseManager]]
icon:calendar[] `Feb 2016 to Nov 2016` +
icon:bank[] Client: Commonwealth Bank Of Australia

Acted as the primary point of contact for on-site technicians during hardware rollouts in CBA branches. 

* Identified patterns in recurring issues and advised leadership team on how to handle them
* Managed communications between first and second level teams to ensure issues were resolved efficiently
* Designed and delivered communications to the first level support team with regular updates on the project
* Created and maintained knowledge articles for first level teams to ensure all issues were known and had quick resolutions
* Created scripts to automate resolutions of most common issues efficiently, reducing handle time for many calls
** Automated (re)installation for most commonly used applications
** Automated fixes for some applications and hardware communication issues
*** In one instance (identifying and resolving receipt printer issues), average resolution times dropped by over 300% by turning a manual troubleshooting process into a single-click function
* Monitored on-going issues and assisted with resolutions
* Unofficially acted as SME for project related issues
* Created SQL and Sharepoint linked reporting spreadsheets for 5 teams to streamline various tasks
** Optimised Knowledge Management reporting by unifying multiple data sources for analysis and progress tracking
** Transformed offline reports for Customer Survey team into live-data reports
** Built a ticket status tracker for first level Service Desk to ensure all SLAs can easily be tracked and kept within acceptable levels

'''

=== icon:play[] Service Desk Analyst at HPE[[ServiceDesk]]
icon:calendar[] `Sep 2015 to Feb 2016` +
icon:bank[] Client: Commonwealth Bank Of Australia

Service Desk Operations – Desktop Team

* General desktop support for >~100 CBA employees daily
* Working with often frustrated, rushed, and angry banking staff, including top level executives who expect the best service
* Fixed general desktop and networking issues e.g.
** Printers
** Software installation, configuration, repairs
** Windows (XP, 7, 8, 10)
** MS Office
** Active Directory
** SCCM
** Group Policy
* Constantly among top 5 analysts for all common service desk statistics
** Low call times
** % resolved on first contact
** SLA compliance
** # of calls taken per day
